/**
 * "The visitor must not be able to tell." Fleet contract section 6.6.
 *
 * The third of the three things that fail if you get them wrong. A prospect
 * inside a sandbox tenant must not learn they are in one, and section 6.6
 * names the exact places it leaks: banners, page titles, email subjects, PDF
 * footers, export filenames, error messages.
 *
 * SCOPE, RE-DERIVED FROM REVISION C
 *
 * Revision B left "anything the visitor can see" undefined, and this file was
 * written against that. Revision C defines it, with one question to apply to
 * each hit:
 *
 *   "would a real paying customer see this same string, in this same place, on
 *    this same screen?"
 *
 * and four verdicts. Two are in scope:
 *
 *   Row 1  the string appears only because the tenant is a sandbox, or in a
 *          message, export or document generated by or on behalf of one
 *   Row 2  the string names the visitor's own account, tenant, session,
 *          environment, plan or data as a demo, sandbox, trial, test, sample
 *          or evaluation. Banned "however ordinary the word is elsewhere in
 *          your product", and the contract's own example is "Your trial
 *          expires in 3 days"
 *
 * and two are not:
 *
 *   Row 3  ordinary product copy every visitor and every real customer sees
 *          identically: a pricing page, a plan name, an FAQ, marketing copy
 *   Row 4  internal strings: a column, a class, a job name, a log line, an API
 *          field. The wire format's own field is `demo`
 *
 * Revision C says so explicitly: "It is not a ban on ordinary commercial
 * vocabulary, and it never was", and "A grep that returns 223 occurrences of
 * 'trial' in storefront copy has returned a grep result, not 223 defects."
 * That settles the repo-wide-grep question the way this file already guessed:
 * `--no-sandbox` is a Chrome launch flag, `.test.ts` is a filename, `PLAID_ENV`
 * carries Plaid's environment, "Book a 20-minute demo" is storefront copy. All
 * four are row 3 or row 4 and stay untouched.
 *
 * WHAT REVISION C CHANGES HERE
 *
 * The row 1 sweep below was right and is unchanged. Row 2 was missing
 * entirely: this file scanned email templates and generated documents and no
 * screen, so it could not see account-state copy. This product has that copy.
 * `components/TrialBanner.tsx` renders "3 days left on your free trial" and
 * "Trial ended" on every dashboard load, which is within a word of the example
 * revision C gives. The second describe block is the row 2 sweep, and its
 * inventory records the verdict for each hit rather than deleting any of them.
 *
 * THE PART OF THIS SWEEP THAT IS STILL NARROW, STATED RATHER THAN FIXED
 *
 * VISITOR_SURFACES reads lib/email/templates, and that is where this
 * product's email copy lives for every message except the ones Supabase's
 * own auth mailer sends. Those are templated in the Supabase dashboard, so
 * their subject and body are not in this repository and no grep here can see
 * them. One of them is the sign-in code from app/login/page.tsx, which is
 * the first email a fleet prospect would ever receive, and another is the
 * firm invitation in lib/email/send-firm-invite.ts.
 *
 * That is a real 6.6 gap and it cannot be closed from here: the fix is to
 * read those templates in the Supabase dashboard before the first sandbox
 * tenant exists. What IS pinned is that the set cannot grow unnoticed. The
 * "Transactional email via Supabase auth" entry in
 * lib/hq/egress-chokepoints.test.ts fails the build when a new file sends
 * mail outside this sweep.
 */

import { describe, it, expect } from "vitest";
import { mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { SANDBOX_SEED } from "./sandbox-seed";

const REPO_ROOT = join(__dirname, "..", "..");

/** Section 6.6's list, verbatim, plus the two phrases it spells out. */
const TELLS = [
  "demo",
  "sandbox",
  "trial",
  "test",
  "sample",
  "evaluation",
  "not a real",
  "for demonstration purposes",
];

/**
 * The surfaces the visitor sees. Each entry is a directory or file whose
 * string content reaches a prospect: an inbox, a PDF, a downloaded file.
 */
const VISITOR_SURFACES = [
  "lib/email/templates",
  "lib/firm/documents/generate.ts",
  "lib/firm/documents/generate-1040.ts",
  "lib/firm/documents/generate-1099.ts",
  "lib/firm/documents/generate-k1.ts",
  "lib/firm/documents/generate-schedule-c.ts",
  "lib/firm/documents/generate-entity-return.ts",
];

/**
 * Surfaces that contain a listed word for a reason unrelated to the sandbox.
 *
 * The reason is required, and it is checked. A bare exclusion would let
 * someone silence a real finding by adding a path, which is how a guard stops
 * being a guard. Same shape as the `definer-grant-ok` markers in
 * scripts/check-definer-grants.mjs.
 *
 * Each entry is also asserted to still exist and still contain the word: an
 * exclusion that has gone stale is coverage quietly lost, and it should fail
 * loudly rather than sit here forever.
 */
const EXCLUSIONS: { file: string; word: string; reason: string }[] = [
  {
    file: "lib/email/templates/beta-invite.ts",
    word: "test",
    reason:
      "Row 3, re-decided under revision C. Every occurrence of the word " +
      "names Apple's TestFlight or the pre-release BUILD: 'invited you to " +
      "test Taxottic', 'help test Taxottic before it ships', 'Beta builds " +
      "expire after 90 days'. None of it names the recipient's account, " +
      "tenant, plan or data, which is what row 2 bans, and revision C's one " +
      "question answers yes: a real paying customer on the beta reads the " +
      "same subject in the same inbox. The previous reason here was " +
      "REACHABILITY, that no sandbox prospect can reach the admin " +
      "beta-invite console, and it carried a warning that reuse by " +
      "provisioning would make the subject a violation on the first send. " +
      "Revision C makes reachability the wrong axis for a row 3 string: it " +
      "is out of scope whoever receives it, so that warning is withdrawn. " +
      "What would put this template in scope is a change to what the words " +
      "describe, not a change to who reads them.",
  },
];

function filesUnder(rel: string): string[] {
  const full = join(REPO_ROOT, rel);
  if (!statSync(full).isDirectory()) return [full];
  const out: string[] = [];
  for (const entry of readdirSync(full)) {
    const child = join(full, entry);
    if (statSync(child).isDirectory()) out.push(...filesUnder(join(rel, entry)));
    else if (entry.endsWith(".ts") && !entry.endsWith(".test.ts")) out.push(child);
  }
  return out;
}

/** Strip // and block comments. A guard that matches a comment is not a guard. */
function stripTsComments(src: string): string {
  return src.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/[^\n]*/g, "");
}

describe("no sandbox tell reaches a visitor-facing surface", () => {
  it("finds the surfaces it is meant to check", () => {
    // Guards the guard. If a rename empties this list the assertion below
    // passes over nothing and reports success for an unchecked codebase.
    const all = VISITOR_SURFACES.flatMap(filesUnder);
    expect(all.length).toBeGreaterThan(8);
    for (const f of all) expect(readFileSync(f, "utf8").length).toBeGreaterThan(0);
  });

  it("keeps every exclusion honest", () => {
    // An exclusion with no reason, or one whose file no longer contains the
    // word, is coverage lost with nothing reporting it.
    for (const e of EXCLUSIONS) {
      expect(e.reason.length, `${e.file}: exclusion has no reason`).toBeGreaterThan(60);
      const src = stripTsComments(
        readFileSync(join(REPO_ROOT, e.file), "utf8"),
      );
      expect(
        new RegExp(`\\b${e.word}\\b`, "i").test(src),
        `${e.file}: excluded for "${e.word}" but no longer contains it, so the exclusion is stale`,
      ).toBe(true);
    }
  });

  it("keeps every tell out of email templates and generated documents", () => {
    const excluded = new Set(EXCLUSIONS.map((e) => `${e.file}: ${e.word}`));
    const hits: string[] = [];
    for (const file of VISITOR_SURFACES.flatMap(filesUnder)) {
      const rel = file.slice(REPO_ROOT.length + 1);
      const src = stripTsComments(readFileSync(file, "utf8"));
      for (const tell of TELLS) {
        const re = new RegExp(`\\b${tell.replace(/ /g, "\\s+")}\\b`, "i");
        if (re.test(src) && !excluded.has(`${rel}: ${tell}`)) {
          hits.push(`${rel}: ${tell}`);
        }
      }
    }
    expect(
      hits,
      "section 6.6: a word on this list in an email subject, a PDF footer or " +
        "a page title tells the prospect they are in a sandbox, and a " +
        "prospect who works that out is the third of the three failures the " +
        "contract names",
    ).toEqual([]);
  });

  it("keeps every tell out of export filenames", () => {
    // Section 6.6 names export filenames specifically. There are two
    // download names in this product and both are constructed from a literal
    // template, so both are readable statically.
    const names = [
      {
        file: "app/api/export/data/route.ts",
        re: /const filename = `([^`]*)`/,
      },
      {
        file: "components/calculators/MileageLogBuilder.tsx",
        re: /a\.download = `([^`]*)`/,
      },
    ];
    for (const { file, re } of names) {
      const src = readFileSync(join(REPO_ROOT, file), "utf8");
      const m = src.match(re);
      expect(m, `${file}: export filename template moved or was renamed`).not.toBeNull();
      for (const tell of TELLS) {
        expect(
          new RegExp(`\\b${tell}\\b`, "i").test(m![1]),
          `${file}: export filename contains "${tell}"`,
        ).toBe(false);
      }
    }
  });

  it("keeps every tell out of the seed fixture itself", () => {
    // The fixture is the copy the prospect reads first. A category called
    // "sample" or a company called "Demo Co" would give the whole thing away
    // on the first screen.
    const text = JSON.stringify(SANDBOX_SEED);
    for (const tell of TELLS) {
      expect(
        new RegExp(`\\b${tell}\\b`, "i").test(text),
        `the sandbox seed contains "${tell}"`,
      ).toBe(false);
    }
  });
});

/**
 * Section 6.6 row 2: copy that names the visitor's own account as a trial.
 *
 * This block is new for revision C. The rule it implements is one sentence:
 * a string that names the visitor's own account, tenant, session, environment,
 * plan or data as a demo, sandbox, trial, test, sample or evaluation is banned
 * "however ordinary the word is elsewhere in your product". The contract's own
 * example, "Your trial expires in 3 days", is a tell "even on a product that
 * sells trials". This product sells trials.
 *
 * The scan is prose only. A `data-testid`, an import path, a `.test(` regex
 * call and a component called `TestPushButton` are row 4 internals, so they are
 * removed before matching rather than excluded afterwards. What is left is the
 * text a signed-in visitor actually reads, and each hit carries its verdict.
 */
describe("no account-state copy names the visitor's own plan as a trial", () => {
  /**
   * Route trees a signed-in visitor reaches, plus every shared component.
   * The public marketing trees (/pricing, /guides, /compare, /help, /legal,
   * /book, /example) are deliberately absent: revision C row 3 puts them out
   * of scope, and 223 occurrences of "trial" in storefront copy is a grep
   * result rather than 223 defects.
   */
  const ACCOUNT_SURFACES = [
    "components",
    "app/dashboard",
    "app/c",
    "app/personal",
    "app/billing",
    "app/settings",
    "app/account",
    "app/onboarding",
    "app/mileage",
    "app/goals",
    "app/reminders",
    "app/bella",
    "app/firm",
    "app/watch",
    "app/beta",
  ];

  type Verdict = "banned" | "not in scope";

  /**
   * Every hit, with the verdict revision C's one question produces for it.
   * Exact set equality: a new hit is a new screen naming the visitor's account
   * state, and it has to be classified by a person rather than absorbed.
   */
  const INVENTORY: { file: string; word: string; verdict: Verdict; note: string }[] =
    [
      {
        file: "components/TrialBanner.tsx",
        word: "trial",
        verdict: "banned",
        note:
          "THE FINDING. Renders 'N days left on your free trial.', '1 day left " +
          "on your free trial.', 'Your free trial has ended.', 'Trial active' " +
          "and 'Trial ended' on the dashboard, the personal forecast and the " +
          "native fallback. Revision C row 2 bans exactly this shape and gives " +
          "'Your trial expires in 3 days' as the example. It cannot be gated " +
          "today: the gate reads companies.sandbox and nothing reads that " +
          "column yet. It is sequenced by the assertion in " +
          "lib/hq/elevated-call-sites.test.ts that nothing creates a sandbox " +
          "tenant, so provisioning cannot ship while this banner is ungated.",
      },
      {
        file: "components/UserMenu.tsx",
        word: "trial",
        verdict: "not in scope",
        note:
          "Row 4. 'No paid features (expired / trial)' is a hint in the " +
          "super-admin plan preview switcher, rendered only when previewPlan " +
          "is wired by an operator. A prospect never holds super-admin, so it " +
          "is not on any surface a sandbox tenant reaches.",
      },
      {
        file: "components/TestPushButton.tsx",
        word: "test",
        verdict: "not in scope",
        note:
          "Row 3. 'Send a test push' on /settings/security is a diagnostic " +
          "every real customer has and sees identically. It says nothing about " +
          "the tenant, and removing it would degrade the product for everyone " +
          "to conceal nothing from anyone.",
      },
      {
        file: "components/forecast/BenefitTiles.tsx",
        word: "test",
        verdict: "not in scope",
        note:
          "Row 3. 'physical-presence test' is the IRC term for the foreign " +
          "earned income exclusion qualification. Ordinary tax vocabulary that " +
          "every real customer reads in the same tile.",
      },
      {
        file: "components/mileage/DiagnoseClient.tsx",
        word: "test",
        verdict: "not in scope",
        note:
          "Row 3. 'Tracker self-test in progress.' names the tracker's own " +
          "diagnostic run, which every real customer can start. It describes a " +
          "feature, not the tenant.",
      },
      {
        file: "app/mileage/diagnose/page.tsx",
        word: "test",
        verdict: "not in scope",
        note:
          "Row 3. The heading over the same diagnostic. Same reasoning as the " +
          "component above.",
      },
      {
        file: "components/HeroInstrument.tsx",
        word: "sample",
        verdict: "not in scope",
        note:
          "Row 3. The 'Sample' trailing label on the marketing hero's " +
          "instrument panel is shown to every visitor of the home page, " +
          "paying or not, identically. It marks the fixed illustrative " +
          "figures the panel always renders, not the visitor's own account, " +
          "plan or data, so revision C's one question answers yes: a real " +
          "paying customer sees this same label on this same public marketing " +
          "screen before they ever sign in.",
      },
    ];

  function tsxUnder(relDir: string): string[] {
    const full = join(REPO_ROOT, relDir);
    const out: string[] = [];
    for (const entry of readdirSync(full)) {
      const child = join(full, entry);
      if (statSync(child).isDirectory()) out.push(...tsxUnder(join(relDir, entry)));
      else if (/\.tsx$/.test(entry) && !/\.(test|spec|ct\.spec|ct\.fixture)\.tsx$/.test(entry)) {
        out.push(child);
      }
    }
    return out;
  }

  it("skips *.ct.fixture.tsx but still scans a real component", () => {
    // A component-test FIXTURE is scaffolding that never ships and that
    // legitimately mounts the real account surfaces to photograph them.
    // Found 2026-09-03: a dashboard fixture mounting TrialBanner tripped
    // this block on "free trial" and lib/app-store/purchase-controls on a
    // /billing link. Pinned with synthetic files under the repo root, so
    // the skip cannot rot silently in either direction.
    const rel = `.walker-probe-${process.pid}`;
    const dir = join(REPO_ROOT, rel);
    mkdirSync(dir, { recursive: true });
    try {
      writeFileSync(join(dir, "Thing.ct.fixture.tsx"), "<p>Your free trial has ended.</p>\n");
      writeFileSync(join(dir, "Thing.ct.spec.tsx"), "<p>Your free trial has ended.</p>\n");
      writeFileSync(join(dir, "Thing.tsx"), "<p>Your free trial has ended.</p>\n");
      expect(tsxUnder(rel).map((f) => basename(f))).toEqual(["Thing.tsx"]);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  /**
   * The prose a signed-in visitor reads: string literals and JSX text, with
   * every row 4 internal removed first. Requiring two adjacent words drops
   * identifiers and single-token attribute values, which is what separates
   * "Your free trial has ended." from `trialState`.
   */
  function visibleProse(file: string): string {
    let src = stripTsComments(readFileSync(file, "utf8"));
    src = src.replace(/data-testid=("[^"]*"|\{[^}]*\})/g, ""); // test hooks
    src = src.replace(/\bimport[^;]*;/g, ""); //                 module paths
    src = src.replace(/\.test\s*\(/g, ".matches("); //           RegExp.test
    const parts: string[] = [];
    for (const m of src.matchAll(
      /"([^"\\]{2,200})"|'([^'\\]{2,200})'|`([^`\\$]{2,200})`/g,
    )) {
      parts.push(m[1] ?? m[2] ?? m[3]);
    }
    for (const m of src.matchAll(/>([^<>{}]{3,200})</g)) parts.push(m[1]);
    return parts.filter((p) => /[a-z] [a-z]/i.test(p)).join("\n");
  }

  function scan(): string[] {
    const hits: string[] = [];
    for (const dir of ACCOUNT_SURFACES) {
      for (const file of tsxUnder(dir)) {
        const prose = visibleProse(file);
        for (const tell of TELLS) {
          const re = new RegExp(`\\b${tell.replace(/ /g, "\\s+")}\\b`, "i");
          if (re.test(prose)) {
            hits.push(`${file.slice(REPO_ROOT.length + 1)}: ${tell}`);
          }
        }
      }
    }
    return hits.sort();
  }

  it("reads a realistic number of signed-in screens", () => {
    // Guards the guard. A set comparison against an empty scan passes and
    // proves nothing, and this scan is the whole of the row 2 sweep.
    const files = ACCOUNT_SURFACES.flatMap(tsxUnder);
    expect(files.length).toBeGreaterThan(100);
  });

  it("reads prose and not identifiers", () => {
    // Mutation-tested. Without the two adjacent words rule this scan returns
    // every file with a `data-testid` and the inventory becomes unmaintainable
    // noise, which is the failure mode revision C spends a page warning about.
    expect(visibleProse(join(REPO_ROOT, "components/TrialBanner.tsx"))).toMatch(
      /free trial has ended/,
    );
    expect(
      visibleProse(join(REPO_ROOT, "components/TrialBanner.tsx")),
    ).not.toMatch(/TrialState/);
  });

  it("classifies every hit, and has no unclassified one", () => {
    expect(
      scan(),
      "a signed-in screen now carries one of section 6.6's words in prose. " +
        "Apply revision C's question to it: would a real paying customer see " +
        "this same string, in this same place, on this same screen? If yes it " +
        "is row 3 and belongs in the inventory as not in scope. If it names " +
        "the visitor's own account, plan or data, it is row 2 and is banned " +
        "for a sandbox tenant however ordinary the word is elsewhere.",
    ).toEqual(INVENTORY.map((e) => `${e.file}: ${e.word}`).sort());
  });

  it("gives a reason for every verdict, and still records the banned one", () => {
    for (const e of INVENTORY) {
      expect(e.note.length, `${e.file}: verdict has no reason`).toBeGreaterThan(60);
    }
    // The banned entry is the finding this block exists to carry. Silently
    // downgrading it to "not in scope" would leave the sweep green over a
    // known tell, which is how a guard stops being a guard.
    const banned = INVENTORY.filter((e) => e.verdict === "banned").map((e) => e.file);
    expect(
      banned,
      "the section 6.6 row 2 finding was reclassified. It is only closed when " +
        "the banner is gated on the tenant flag, not when the note changes.",
    ).toEqual(["components/TrialBanner.tsx"]);
  });
});
