-- ~40 new deduction categories: commonly-overlooked business
-- expenses, the rest of Schedule A, and 8 federal tax credits.
-- Every row carries IRS Pub + IRC + irs.gov URL where applicable so
-- the per-row citation strip in the import-review row stays accurate.
-- Inserts grouped by display_group so the picker buckets them.
-- See migrations 20260524 / 20260525 for the prerequisite scope +
-- column changes.

insert into public.deduction_categories
  (code, label, description, scope, schedule_c_line, irc_section,
   irs_pub, irs_url, is_meal, is_vehicle, display_order,
   is_typically_recurring, display_group)
values
  ('liability_insurance', 'General liability / E&O insurance',
   'Premiums for commercial general liability, professional liability (E&O), product liability. Schedule C Line 15.',
   'business', 'Line 15', '§162', 'Pub 535',
   'https://www.irs.gov/forms-pubs/about-publication-535',
   false, false, 71, true, 'Insurance'),
  ('workers_comp_insurance', 'Workers comp insurance',
   'Required in most states for businesses with employees. Premiums are deductible on Schedule C Line 15.',
   'business', 'Line 15', '§162', 'Pub 535',
   'https://www.irs.gov/forms-pubs/about-publication-535',
   false, false, 72, true, 'Insurance'),
  ('vehicle_insurance', 'Vehicle insurance (business portion)',
   'Auto insurance on a business-use vehicle, prorated by business-use %. Schedule C Line 15 if using actual-expense method.',
   'business', 'Line 15', '§162', 'Pub 463',
   'https://www.irs.gov/forms-pubs/about-publication-463',
   false, true, 73, true, 'Insurance'),
  ('group_health_insurance', 'Employee group health insurance',
   'Health insurance premiums you pay for employees (not the self-employed owner). Schedule C Line 14.',
   'business', 'Line 14', '§162', 'Pub 535',
   'https://www.irs.gov/forms-pubs/about-publication-535',
   false, false, 61, true, 'Employees & payroll'),
  ('payroll_processing', 'Payroll processing fees',
   'Gusto, ADP, Paychex, Rippling, QuickBooks Payroll subscription + per-employee fees. Schedule C Line 27a.',
   'business', 'Line 27a', '§162', 'Pub 535',
   'https://www.irs.gov/forms-pubs/about-publication-535',
   false, false, 62, true, 'Employees & payroll'),
  ('unemployment_taxes', 'Federal + state unemployment taxes',
   'FUTA (federal) + SUTA (state) employer-paid unemployment insurance taxes. Schedule C Line 23.',
   'business', 'Line 23', '§164', 'Pub 535',
   'https://www.irs.gov/forms-pubs/about-publication-535',
   false, false, 152, true, 'Employees & payroll'),
  ('lodging', 'Hotel / lodging (business travel)',
   'Hotels, Airbnb, motels while travelling for business away from your tax home. 100% deductible. Schedule C Line 24a.',
   'business', 'Line 24a', '§162', 'Pub 463',
   'https://www.irs.gov/forms-pubs/about-publication-463',
   false, false, 161, true, 'Travel, meals & gifts'),
  ('per_diem_meals', 'Per-diem meals (business travel)',
   'Standard per-diem meal allowance while travelling. 50% deductible.',
   'business', 'Line 24b', '§274', 'Pub 463',
   'https://www.irs.gov/forms-pubs/about-publication-463',
   true, false, 171, true, 'Travel, meals & gifts'),
  ('conference_fees', 'Conference / trade show fees',
   'Registration for industry conferences, summits, trade shows.',
   'business', 'Line 27a', '§162', 'Pub 535',
   'https://www.irs.gov/forms-pubs/about-publication-535',
   false, false, 162, true, 'Travel, meals & gifts'),
  ('fuel', 'Fuel / gas (actual-expense method)',
   'Gasoline, diesel, EV charging. ONLY deductible separately under the actual-expense method.',
   'business', 'Line 9', '§162', 'Pub 463',
   'https://www.irs.gov/forms-pubs/about-publication-463',
   false, true, 23, true, 'Vehicle'),
  ('vehicle_repairs', 'Vehicle repairs (actual-expense method)',
   'Oil changes, tires, repairs on a business-use vehicle, prorated by business %.',
   'business', 'Line 9', '§162', 'Pub 463',
   'https://www.irs.gov/forms-pubs/about-publication-463',
   false, true, 24, false, 'Vehicle'),
  ('vehicle_lease', 'Vehicle lease (business portion)',
   'Monthly lease payments on a business-use vehicle, prorated by business %.',
   'business', 'Line 20a', '§162', 'Pub 463',
   'https://www.irs.gov/forms-pubs/about-publication-463',
   false, true, 121, true, 'Vehicle'),
  ('cleaning_services', 'Cleaning / janitorial services',
   'Office cleaning, janitorial, sanitizing.',
   'business', 'Line 21', '§162', 'Pub 535',
   'https://www.irs.gov/forms-pubs/about-publication-535',
   false, false, 131, true, 'Repairs & maintenance'),
  ('security_monitoring', 'Security / alarm monitoring',
   'Commercial security system installation + monthly monitoring.',
   'business', 'Line 25', '§162', 'Pub 535',
   'https://www.irs.gov/forms-pubs/about-publication-535',
   false, false, 182, true, 'Utilities, phone & internet'),
  ('trash_disposal', 'Trash / waste disposal',
   'Commercial trash + recycling pickup.',
   'business', 'Line 25', '§162', 'Pub 535',
   'https://www.irs.gov/forms-pubs/about-publication-535',
   false, false, 183, true, 'Utilities, phone & internet'),
  ('snow_landscaping', 'Snow removal / landscaping (business property)',
   'Snow plowing, lawn care, landscape maintenance on business property.',
   'business', 'Line 21', '§162', 'Pub 535',
   'https://www.irs.gov/forms-pubs/about-publication-535',
   false, false, 132, true, 'Repairs & maintenance'),
  ('storage_rental', 'Storage unit / off-site storage',
   'Storage unit, warehouse space rented separately from the main office.',
   'business', 'Line 20b', '§162', 'Pub 535',
   'https://www.irs.gov/forms-pubs/about-publication-535',
   false, false, 111, true, 'Rent & lease'),
  ('coworking_membership', 'Coworking space membership',
   'WeWork, Industrious, local coworking memberships.',
   'business', 'Line 20b', '§162', 'Pub 535',
   'https://www.irs.gov/forms-pubs/about-publication-535',
   false, false, 112, true, 'Rent & lease'),
  ('professional_certs', 'Professional certifications & licenses',
   'CPA exam fees, bar exam, real estate license renewal, CDL, professional designations.',
   'business', 'Line 23', '§162', 'Pub 535',
   'https://www.irs.gov/forms-pubs/about-publication-535',
   false, false, 153, false, 'Education & training'),
  ('continuing_education', 'Continuing education (CE / CPE)',
   'Required continuing education credits to maintain a license.',
   'business', 'Line 27a', '§162', 'Pub 970',
   'https://www.irs.gov/forms-pubs/about-publication-970',
   false, false, 211, true, 'Education & training'),
  ('industry_journals', 'Industry journals & publications',
   'Subscriptions to trade journals, industry magazines, research publications.',
   'business', 'Line 27a', '§162', 'Pub 535',
   'https://www.irs.gov/forms-pubs/about-publication-535',
   false, false, 212, true, 'Education & training'),
  ('startup_costs', 'Startup costs (first $5,000)',
   'Costs incurred BEFORE the business opens. First $5,000 deductible the year operations start; rest amortized over 15 years.',
   'business', 'Line 27a', '§195', 'Pub 535',
   'https://www.irs.gov/forms-pubs/about-publication-535',
   false, false, 241, false, 'Startup & formation'),
  ('organizational_costs', 'Organizational costs (entity formation)',
   'Costs to organize a corporation/LLC/partnership. First $5,000 deductible; rest amortized 15 years.',
   'business', 'Line 27a', '§248', 'Pub 535',
   'https://www.irs.gov/forms-pubs/about-publication-535',
   false, false, 242, false, 'Startup & formation'),
  ('web_hosting_domain', 'Web hosting & domain registration',
   'Vercel, AWS, Netlify, Cloudflare, GoDaddy domain renewals, SSL certs.',
   'business', 'Line 18', '§162', 'Pub 535',
   'https://www.irs.gov/forms-pubs/about-publication-535',
   false, false, 106, true, 'Software & subscriptions'),
  ('cloud_storage', 'Cloud storage & backup',
   'Dropbox Business, Google Workspace storage, Backblaze, iCloud Business.',
   'business', 'Line 18', '§162', 'Pub 535',
   'https://www.irs.gov/forms-pubs/about-publication-535',
   false, false, 107, true, 'Software & subscriptions'),
  ('charity_noncash', 'Charitable contributions — non-cash',
   'Donated goods (clothing, furniture, vehicles). Items > $500 require Form 8283; > $5,000 need an appraisal.',
   'personal', null, '§170', 'Pub 526',
   'https://www.irs.gov/forms-pubs/about-publication-526',
   false, false, 1011, false, 'Charitable giving'),
  ('medical_mileage', 'Medical mileage',
   '$0.21/mile (2024 rate) for driving to/from medical appointments. Schedule A, itemized, subject to 7.5% AGI floor.',
   'personal', null, '§213', 'Pub 502',
   'https://www.irs.gov/forms-pubs/about-publication-502',
   false, true, 1041, false, 'Medical (Sched A)'),
  ('dental_vision', 'Dental & vision expenses',
   'Out-of-pocket dental, vision, hearing aids, prescription glasses/contacts.',
   'personal', null, '§213', 'Pub 502',
   'https://www.irs.gov/forms-pubs/about-publication-502',
   false, false, 1042, false, 'Medical (Sched A)'),
  ('long_term_care_insurance', 'Long-term care insurance premiums',
   'Premiums for qualified long-term care policies. Schedule A medical, subject to age-based annual caps.',
   'personal', null, '§213(d)', 'Pub 502',
   'https://www.irs.gov/forms-pubs/about-publication-502',
   false, false, 1043, true, 'Medical (Sched A)'),
  ('mortgage_points', 'Mortgage points paid',
   'Points paid at closing on a primary residence mortgage. Deductible in full the year paid.',
   'personal', null, '§163', 'Pub 936',
   'https://www.irs.gov/forms-pubs/about-publication-936',
   false, false, 1031, false, 'Home & taxes (Sched A)'),
  ('property_tax_personal', 'Property tax on personal residence',
   'Real estate taxes on your primary + secondary residence, capped at $10k SALT total.',
   'personal', null, '§164(b)(6)', 'Pub 530',
   'https://www.irs.gov/forms-pubs/about-publication-530',
   false, false, 1021, true, 'Home & taxes (Sched A)'),
  ('ira_contribution', 'Traditional IRA contribution',
   'Up to $7,000/yr (2024) deductible if income under the phase-out for those with a workplace retirement plan.',
   'personal', null, '§219', 'Pub 590-A',
   'https://www.irs.gov/forms-pubs/about-publication-590-a',
   false, false, 1071, true, 'Adjustments to income'),
  ('educator_expenses', 'Educator expenses ($300 above-the-line)',
   'K-12 teachers, instructors, counselors can deduct up to $300 of unreimbursed classroom expenses.',
   'personal', null, '§62(a)(2)(D)', 'Pub 17',
   'https://www.irs.gov/forms-pubs/about-publication-17',
   false, false, 1072, true, 'Adjustments to income'),
  ('child_tax_credit', 'Child Tax Credit',
   'Up to $2,000 per qualifying child under 17. Phases out above $200k single / $400k joint.',
   'credit', null, '§24', 'Pub 972',
   'https://www.irs.gov/credits-deductions/individuals/child-tax-credit',
   false, false, 3001, false, 'Federal tax credits'),
  ('dependent_care_credit', 'Child & Dependent Care Credit',
   '20-35% of qualifying childcare/dependent-care expenses up to $3,000 (one) or $6,000 (two+).',
   'credit', null, '§21', 'Pub 503',
   'https://www.irs.gov/forms-pubs/about-publication-503',
   false, false, 3002, false, 'Federal tax credits'),
  ('earned_income_credit', 'Earned Income Tax Credit (EITC)',
   'Refundable credit for low-to-moderate-income workers. Amount depends on filing status + qualifying children.',
   'credit', null, '§32', 'Pub 596',
   'https://www.irs.gov/credits-deductions/individuals/earned-income-tax-credit-eitc',
   false, false, 3003, false, 'Federal tax credits'),
  ('savers_credit', 'Saver credit (retirement savings contributions)',
   '10-50% of retirement contributions (IRA, 401k, etc.) up to $2,000.',
   'credit', null, '§25B', 'Pub 590-A',
   'https://www.irs.gov/credits-deductions/individuals/savers-credit',
   false, false, 3004, false, 'Federal tax credits'),
  ('american_opportunity_credit', 'American Opportunity Credit (education)',
   'Up to $2,500/yr per student for first 4 years of post-secondary education. 40% refundable.',
   'credit', null, '§25A', 'Pub 970',
   'https://www.irs.gov/credits-deductions/individuals/aotc',
   false, false, 3005, false, 'Federal tax credits'),
  ('lifetime_learning_credit', 'Lifetime Learning Credit (education)',
   'Up to $2,000/yr for any post-secondary education or skills courses. Non-refundable.',
   'credit', null, '§25A(c)', 'Pub 970',
   'https://www.irs.gov/credits-deductions/individuals/llc',
   false, false, 3006, false, 'Federal tax credits'),
  ('residential_energy_credit', 'Residential Clean Energy Credit',
   '30% of qualified solar, wind, geothermal, battery storage installed on a home.',
   'credit', null, '§25D', 'Pub 17',
   'https://www.irs.gov/credits-deductions/residential-clean-energy-credit',
   false, false, 3007, false, 'Federal tax credits'),
  ('foreign_tax_credit', 'Foreign Tax Credit',
   'Credit for income taxes paid to a foreign country (dual-resident, foreign-income earners).',
   'credit', null, '§901', 'Pub 514',
   'https://www.irs.gov/forms-pubs/about-publication-514',
   false, false, 3008, false, 'Federal tax credits')
on conflict (code) do nothing;
