-- Phase 5 of the enterprise build: documents + e-signature.
--
-- One table (firm_documents) tracks every document the firm has
-- generated, uploaded, or sent for signature. The actual file
-- bytes live in Supabase Storage in a `firm-documents` bucket
-- (NOT created by this migration — bucket creation is a one-time
-- console operation; see docs/FIRM_DOCUMENTS_RUNBOOK.md for the
-- exact RLS to apply).
--
-- E-signature provider abstraction:
-- ---------------------------------
-- Documents that need a signature get sent to one of two providers
-- based on firm tier:
--   - Documenso (self-hosted): default for all firms. Zero per-sig
--     fees. Audit trail lives in our DB via Documenso webhook.
--   - DocuSign: enterprise tier only. Industry-standard signal for
--     bigger firms; we charge them a margin on top of DocuSign
--     envelopes.
-- The `provider` column + `provider_envelope_id` record which
-- envelope at which provider corresponds to the local doc row, so
-- the webhook can look it up in one query.

-- ----------------------------------------------------------------
-- firm_documents
-- ----------------------------------------------------------------

do $$ begin
  create type public.firm_document_kind as enum (
    -- Firm-prepared (firm-side)
    'engagement_letter',
    'organizer',
    'invoice',
    'receipt',
    'firm_letter',
    'internal_memo',
    -- Tax forms (firm-prepared from client books)
    'schedule_c_draft',
    'schedule_e_draft',
    'k1_draft',
    '1099_nec_draft',
    '1099_misc_draft',
    '1040_draft',
    'tax_return_packet',
    -- Client-uploaded
    'client_upload_w2',
    'client_upload_1099',
    'client_upload_receipt',
    'client_upload_prior_return',
    'client_upload_other',
    -- Catch-all for misc
    'manual_upload'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.firm_document_status as enum (
    'draft',
    'ready_for_review',
    'awaiting_signature',
    'signed',
    'filed',
    'sent_to_client',
    'archived',
    'error'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.firm_document_provider as enum (
    'manual',       -- uploaded by a human, no e-sig flow
    'generated',    -- auto-generated by our template engine
    'documenso',    -- sent to Documenso for signature
    'docusign'      -- sent to DocuSign for signature
  );
exception when duplicate_object then null; end $$;

create table if not exists public.firm_documents (
  id uuid primary key default gen_random_uuid(),
  firm_id uuid not null references public.firms(id) on delete cascade,
  -- engagement_id optional: firm-internal docs (internal memos,
  -- training material) don't tie to a specific engagement.
  engagement_id uuid references public.firm_engagements(id) on delete set null,
  -- company_id derived from engagement when present; left explicit
  -- so a client-uploaded doc (no engagement yet) can still link to
  -- their company.
  company_id uuid references public.companies(id) on delete set null,
  uploader_user_id uuid references public.profiles(id) on delete set null,
  kind public.firm_document_kind not null,
  status public.firm_document_status not null default 'draft',
  provider public.firm_document_provider not null default 'manual',
  -- E-signature provider envelope ID (Documenso doc ID / DocuSign
  -- envelopeId). NULL when status != awaiting_signature/signed.
  provider_envelope_id text,
  -- Path within the `firm-documents` storage bucket. Pattern:
  --   firms/{firm_id}/engagements/{engagement_id}/{doc_id}.{ext}
  -- or firms/{firm_id}/internal/{doc_id}.{ext} for engagement=null.
  storage_path text not null,
  filename text not null,
  content_type text not null default 'application/pdf',
  size_bytes bigint default 0,
  -- Tax year for tax-form docs; NULL for engagement letters,
  -- invoices, etc.
  tax_year int,
  -- Free-form notes from the preparer.
  notes text,
  -- Hash for tamper-evidence (sha256 hex of the bytes at upload).
  sha256 text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  sent_at timestamptz,    -- when sent for signature
  signed_at timestamptz,  -- when fully signed
  filed_at timestamptz    -- when filed with IRS / state
);

create index if not exists firm_documents_firm_idx
  on public.firm_documents (firm_id, created_at desc);
create index if not exists firm_documents_engagement_idx
  on public.firm_documents (engagement_id, created_at desc)
  where engagement_id is not null;
create index if not exists firm_documents_company_idx
  on public.firm_documents (company_id, created_at desc)
  where company_id is not null;
create index if not exists firm_documents_envelope_idx
  on public.firm_documents (provider, provider_envelope_id)
  where provider_envelope_id is not null;
create index if not exists firm_documents_status_idx
  on public.firm_documents (firm_id, status, created_at desc);

alter table public.firm_documents enable row level security;

-- Firm owners + managers see all firm docs.
drop policy if exists "firm admins read all firm documents"
  on public.firm_documents;
create policy "firm admins read all firm documents"
  on public.firm_documents
  for select
  using (
    public.is_firm_owner_or_manager(firm_id)
    or public.is_super_admin()
  );

-- Preparers see docs on engagements they're assigned to.
drop policy if exists "firm preparers read assigned engagement docs"
  on public.firm_documents;
create policy "firm preparers read assigned engagement docs"
  on public.firm_documents
  for select
  using (
    public.is_firm_member(firm_id)
    and engagement_id is not null
    and exists (
      select 1 from public.firm_engagements
      where id = firm_documents.engagement_id
        and assigned_preparer_id = auth.uid()
    )
  );

-- Clients see docs on their own company (e.g. their engagement
-- letter is theirs to view + sign).
drop policy if exists "client reads own company docs"
  on public.firm_documents;
create policy "client reads own company docs"
  on public.firm_documents
  for select
  using (
    company_id is not null
    and public.is_company_manager(company_id)
  );

-- Inserts: firm members can create docs for their firm; clients
-- can upload to a company they manage. Path validation is enforced
-- by the helper below — direct INSERT skips it, which is fine
-- because RLS gates by firm/company membership.
drop policy if exists "firm members insert firm docs"
  on public.firm_documents;
create policy "firm members insert firm docs"
  on public.firm_documents
  for insert
  with check (
    public.is_firm_member(firm_id)
    or (company_id is not null and public.is_company_manager(company_id))
  );

-- Updates: same scope as insert. The webhook handler updates rows
-- via service-role so RLS doesn't apply there.
drop policy if exists "firm members update firm docs"
  on public.firm_documents;
create policy "firm members update firm docs"
  on public.firm_documents
  for update
  using (
    public.is_firm_owner_or_manager(firm_id)
    or (company_id is not null and public.is_company_manager(company_id))
  );

-- ----------------------------------------------------------------
-- Updated-at trigger so we don't have to remember in app code.
-- ----------------------------------------------------------------
create or replace function public.firm_documents_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists firm_documents_touch_updated_at on public.firm_documents;
create trigger firm_documents_touch_updated_at
  before update on public.firm_documents
  for each row execute function public.firm_documents_touch_updated_at();

-- Add to realtime publication so the per-engagement document
-- panel updates live as docs are uploaded / signed / filed.
do $$ begin
  alter publication supabase_realtime add table public.firm_documents;
exception when others then null; end $$;
